### ISSUE TITLE
where are the libs and bins?

### ISSUE THREAD

**Issue by wuqiangch** [handong1587/Caffe_demo#1]
Can you share your libs and bins:here is my email---wuqiang_jobs@163.com.

**Comment by handong1587** [comment]
Hi, I upload libs and bins here: http://pan.baidu.com/share/link?shareid=1158714047&uk=1762114780
This is just a simple Caffe demo. I recommend you use a Microsoft maintained Windows/Linux Caffe:
https://github.com/Microsoft/caffe
Or this:
https://github.com/happynear/caffe-windows

**Comment by wuqiangch** [comment]
Thanks for your help.  I only use it for a deme like you.
