### ISSUE TITLE
Have you test it on window x64?

### ISSUE THREAD

**Issue by wuqiangch** [handong1587/Caffe_demo#2]
Have you test it on window x64. I want to test it on windows x64. I only to change all libs and bins of x86 to x64?  I also have a problem . I use vs2015 to build protobuf . I only get the protobuf.lib  and no protobuf.dll.  I search the problem and can't get the solution.

**Comment by handong1587** [comment]
I haven't tested it on Windows x64, but you certainly can port it to x64. Please replace those libs/bins with x64 version.
About the protobuf lib/dll issue please follow the official instructions.
https://github.com/google/protobuf/blob/master/cmake/README.md

**Comment by wuqiangch** [comment]
@handong1587  vs2015  x64 is ok now. But there is another problem:upgrade_proto.cpp:935] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: bvlc_reference_caffenet.caffemodel.  which version of caffe do you use ?

**Comment by handong1587** [comment]
Hi @wuqiangch I created this demo at December, 2015, so I should use the then latest Caffe at that time. Howerver it is an out-dated version for now, I think you might want to use the latest version (I haven't tested it yet but I just surpose that old Caffe should be able to parse the new official caffemodel). Anyway porting old Caffe to new one should be a better choice without a doubt.

**Comment by wuqiangch** [comment]
@handong1587 everything is OK now. for you changed some code in upgrade_proto.cpp and I changed them back. Thanks!!!
